#东营西城
mqtt:
  hostUrl: tcp://10.84.32.166:1883
  username: admin
  password: wanda@1234
  client-id: IOT-EPC-Pj3705020020-ly
  cleanSession: true
  reconnect: true
  keepAlive: 100
  isOpen: true
  qos: 1
  sendtopic: project/gcId/report
  setdownTopic: cloud/gcid/setdown

spring:
    #redis配置
  redis:
    host: 10.84.32.166
    port: 16379
    password:

beanName: opcCommunication

server:
  port: 9030
#广场ID及GatewayId
epc:
  gatewayId: LY
  gcId: 3705020020
  subsystem: lzqk/
  threadNum: 10
opc:
  host: 10.84.32.34
  user: administrator
  password: dywd201500815
  #域 为空即可
  domain: ""
  #注册表id
  clsid: 6E6170F0-FF2D-11D2-8087-00105AA8F840
  progId: ""
  isNotBoolean: 0
