mqtt:
  hostUrl: tcp://127.0.0.1:1883
  username: admin
  password: wanda@1234
  client-id: IOT-EPC-Pj3413020010-ba
  cleanSession: true
  reconnect: true
  keepAlive: 100
  isOpen: true
  qos: 1
  sendtopic: project/gcId/report
  setdownTopic: cloud/gcid/setdown

spring:
  #redis配置
  redis:
    host: 127.0.0.1
    port: 16379
    password:

beanName: opcCommunication

server:
  port: 9031

#广场ID及GatewayId
epc:
  gatewayId: LY
  gcId: 3413020010
  subsystem: ryxt/lzqk/ktmd/hjpz/jsxt/psxt/ddc/
  threadNum: 10
opc:
  host: 192.168.13.100
  user: administrator
  password: wanda@1234
  #域 为空即可
  domain: ""
  #注册表id
  clsid: 6764a030-070c-11d3-81d6-0060975858be
  progId: ""
